ALTER TABLE fake_notifications ADD COLUMN IF NOT EXISTS note TEXT NULL DEFAULT NULL AFTER price;
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='fake_notifications' AND TABLE_SCHEMA='driver_db';
